version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /tools
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    open-pull-requests-limit: 3
